### ISSUE TITLE
[conda installation] ImportError: libmkl_sequential.so.2: undefined symbol

### ISSUE THREAD

**Issue by lxsteiner** [samhorsfield96/ggCaller#10]
Hi,

tried to install with conda recipe from bioconda:
`mamba create -n ggcaller_env -c defaults -c bioconda -c conda-forge ggcaller
`
after installation it fails:
```
$ ggcaller -h
Traceback (most recent call last):
  File "miniconda3/usr/envs/ggcaller_env/bin/ggcaller", line 7, in <module>
    from ggCaller.__main__ import main
  File "miniconda3/usr/envs/ggcaller_env/lib/python3.10/site-packages/ggCaller/__main__.py", line 6, in <module>
    import ggCaller_cpp
ImportError: miniconda3/usr/envs/ggcaller_env/lib/python3.10/site-packages/../../libmkl_sequential.so.2: undefined symbol: mkl_graph_mxm_gus_phase2_plus_second_fp32_def_i64_i32_fp32
```

Here are the package versions inside the environment:
```
$ conda list
# packages in environment at ggcaller_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
argcomplete               1.12.3             pyhd3eb1b0_0
argh                      0.26.2          py310h06a4308_0
bcbio-gff                 0.7.0              pyh7cba7a3_0    bioconda
bifrost                   1.2.1                h43eeafb_0    bioconda
biopython                 1.78            py310h7f8727e_0
blas                      1.0                    openblas
blast                     2.14.1          pl5321h6f7f691_0    bioconda
boost-cpp                 1.78.0               h2c5509c_4    conda-forge
bottleneck                1.3.5           py310ha9d4c09_0
brotli                    1.0.9                h5eee18b_7
brotli-bin                1.0.9                h5eee18b_7
bx-python                 0.10.0          py310h551a815_0    bioconda
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.19.0               h5eee18b_0
ca-certificates           2023.05.30           h06a4308_0
cd-hit                    4.8.1                h43eeafb_9    bioconda
cffi                      1.15.1          py310h5eee18b_3
contourpy                 1.0.5           py310hdb19cb5_0
cudatoolkit               11.3.1               h2bc3f7f_2
cudnn                     8.9.2.26               cuda11_0
cupti                     11.3.1                        0
curl                      8.1.1                hdbd6064_2
cycler                    0.11.0             pyhd3eb1b0_0
diamond                   2.1.8                h43eeafb_0    bioconda
entrez-direct             16.2                 he881be0_1    bioconda
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               h4a9f257_0
future                    0.18.3          py310h06a4308_0
gettext                   0.21.1               h27087fc_0    conda-forge
gffutils                  0.12               pyh7cba7a3_0    bioconda
ggcaller                  1.3.4           py310h54719a5_0    bioconda
giflib                    5.2.1                h5eee18b_3
hmmer                     3.3.2                hdbdd923_4    bioconda
icu                       73.2                 h59595ed_0    conda-forge
importlib-metadata        4.11.3          py310h06a4308_0
importlib_metadata        4.11.3               hd3eb1b0_0
intbitset                 2.4.1           py310h5764c6d_3    conda-forge
joblib                    1.2.0           py310h06a4308_0
jpeg                      9e                   h5eee18b_1
kiwisolver                1.4.4           py310h6a678d5_0
krb5                      1.20.1               h143b758_1
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libbrotlicommon           1.0.9                h5eee18b_7
libbrotlidec              1.0.9                h5eee18b_7
libbrotlienc              1.0.9                h5eee18b_7
libcurl                   8.1.1                h251f7ec_2
libdeflate                1.17                 h5eee18b_0
libedit                   3.1.20221030         h5eee18b_0
libev                     4.33                 h7f8727e_1
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            11.2.0               h00389a5_1
libgfortran5              11.2.0               h1234567_1
libhwloc                  2.9.2           default_h554bfaf_1009    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libidn2                   2.3.4                h5eee18b_0
libnghttp2                1.52.0               h2d74bed_1
libnsl                    2.0.0                h5eee18b_0
libopenblas               0.3.21               h043d6bf_0
libpng                    1.6.39               h5eee18b_0
libprotobuf               3.20.3               he621ea3_0
libsqlite                 3.43.0               h2797004_0    conda-forge
libssh2                   1.10.0               hdbd6064_2
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtiff                   4.5.0                h6a678d5_2
libunistring              0.9.10               h27cfd23_0
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp                   1.2.4                h11a3e52_1
libwebp-base              1.2.4                h5eee18b_1
libxcb                    1.15                 h7f8727e_0
libxml2                   2.11.5               h232c23b_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               16.0.6               h4dfa4b3_0    conda-forge
lz4-c                     1.9.4                h6a678d5_0
mafft                     7.520                h031d066_2    bioconda
magma                     2.7.0                h8db6258_0
matplotlib-base           3.7.1           py310h1128e8f_1
mkl                       2022.2.1         h84fe81f_16997    conda-forge
munkres                   1.1.4                      py_0
ncbi-vdb                  3.0.7                hdbdd923_0    bioconda
ncurses                   6.4                  h6a678d5_0
networkx                  3.1             py310h06a4308_0
ninja                     1.10.2               h06a4308_5
ninja-base                1.10.2               hd09550d_5
numexpr                   2.8.4           py310h757a811_1
numpy                     1.25.2          py310heeff2f4_0
numpy-base                1.25.2          py310h8a23956_0
openssl                   3.1.2                hd590300_0    conda-forge
ossuuid                   1.6.2             hf484d3e_1000    conda-forge
packaging                 23.0            py310h06a4308_0
pandas                    2.0.3           py310h1128e8f_0
pcre                      8.45                 h295c915_0
perl                      5.22.2.1                      0    conda-forge
perl-archive-tar          2.18                          1    bioconda
perl-common-sense         3.74                          0    bioconda
perl-exporter-tiny        0.042                         1    bioconda
perl-json                 2.90                          1    bioconda
perl-json-xs              2.34                          0    bioconda
perl-list-moreutils       0.413                         1    bioconda
perl-threaded             5.32.1               hdfd78af_1    bioconda
perl-uri                  1.71                          0    bioconda
perl-xml-libxml           2.0124                        0    bioconda
perl-xml-namespacesupport 1.11                          0    bioconda
perl-xml-sax              0.99                          0    bioconda
perl-xml-sax-base         1.08                          0    bioconda
pillow                    9.4.0           py310h6a678d5_0
pip                       23.2.1          py310h06a4308_0
pthread-stubs             0.3                  h0ce48e5_1
pycparser                 2.21               pyhd3eb1b0_0
pyfaidx                   0.7.2.1            pyh7cba7a3_1    bioconda
pyparsing                 3.0.9           py310h06a4308_0
python                    3.10.12         hd12c33a_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0
python-edlib              1.3.9           py310h0dbaff4_4    bioconda
python-tzdata             2023.3             pyhd3eb1b0_0
python-wget               3.2                        py_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytorch                   1.13.1          gpu_cuda113py310hde3f150_1
pytz                      2022.7          py310h06a4308_0
pyvcf3                    1.0.3              pyhdfd78af_0    bioconda
pyyaml                    6.0             py310h5eee18b_1
rapidnj                   2.3.2                h4ac6f70_4    bioconda
readline                  8.2                  h5eee18b_0
scipy                     1.11.1          py310heeff2f4_0
seaborn                   0.12.2          py310h06a4308_0
setuptools                68.0.0          py310h06a4308_0
simplejson                3.17.6          py310h7f8727e_0
six                       1.16.0             pyhd3eb1b0_1
snp-sites                 2.5.1                he4a0461_4    bioconda
tbb                       2021.10.0            h00ab1b0_0    conda-forge
tk                        8.6.12               h1ccaba5_0
tqdm                      4.65.0          py310h2f386ee_0
typing-extensions         4.7.1           py310h06a4308_0
typing_extensions         4.7.1           py310h06a4308_0
tzdata                    2023c                h04d1e81_0
uncertainties             3.1.7              pyhd8ed1ab_0    conda-forge
wget                      1.21.4               h251f7ec_1
wheel                     0.38.4          py310h06a4308_0
xorg-compositeproto       0.4.2             h7f98852_1001    conda-forge
xorg-damageproto          1.2.1             h7f98852_1002    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxaw               1.0.14               h7f98852_1    conda-forge
xorg-libxcomposite        0.4.6                h0b41bf4_1    conda-forge
xorg-libxcursor           1.2.0                h0b41bf4_1    conda-forge
xorg-libxdamage           1.1.5                h7f98852_1    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxinerama          1.1.5                h27087fc_0    conda-forge
xorg-libxmu               1.1.3                h7f98852_0    conda-forge
xorg-libxpm               3.5.16               hd590300_0    conda-forge
xorg-libxrandr            1.5.2                h7f98852_1    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-libxt                1.3.0                hd590300_1    conda-forge
xorg-randrproto           1.5.0             h7f98852_1001    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-util-macros          1.19.0               h27cfd23_2
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007
xz                        5.4.2                h5eee18b_0
yaml                      0.2.5                h7b6447c_0
zipp                      3.11.0          py310h06a4308_0
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hc292b87_0
```

System info:
```
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```
Saw in the other closed issues that the biopython version caused issues in some cases? 

Then tried installing from source via the .yml file and the github repo.  After `$ python setup.py install` there were some warnings, but seems to have installed OK so far (at least the help message is printing):
```
miniconda3/usr/envs/ggcaller-1.3.4_env/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
miniconda3/usr/envs/ggcaller-1.3.4_env/lib/python3.9/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(


-- Caffe2: Protobuf version 3.19.6
CMake Warning at miniconda3/usr/envs/ggcaller-1.3.4_env/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  miniconda3/usr/envs/ggcaller-1.3.4_env/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:79 (find_package)


soft/ggCaller/include/sdsl/int_vector.hpp:1081:17: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
 1081 |   : public std::iterator<std::random_access_iterator_tag,
      |                 ^~~~~~~~


soft/ggCaller/include/sdsl/iterators.hpp:23:17: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
   23 |   : public std::iterator<std::random_access_iterator_tag, typename t_rac::value_type, typename t_rac::difference_type>
      |                 ^~~~~~~~


soft/ggCaller/include/sdsl/int_vector.hpp:1081:17: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
 1081 |   : public std::iterator<std::random_access_iterator_tag,
      |                 ^~~~~~~~
```
Plenty of these `[-Wdeprecated-declarations]` warnings... I can provide you with the entire log if interested or relevant; I'm not familiar with the warnings.

Here the package versions in this (hopefully functioning?) environment, for comparison:
```
$ conda list
# packages in environment at ggcaller-1.3.4_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
argcomplete               3.1.1              pyhd8ed1ab_0    conda-forge
argh                      0.27.2             pyhd8ed1ab_0    conda-forge
bcbio-gff                 0.7.0              pyh7cba7a3_0    bioconda
bifrost                   1.2.1                h43eeafb_0    bioconda
binutils                  2.40                 hdd6e379_0    conda-forge
binutils_impl_linux-64    2.40                 hf600244_0    conda-forge
binutils_linux-64         2.40                 hbdbef99_1    conda-forge
biopython                 1.80             py39hb9d737c_0    conda-forge
blast                     2.14.1          pl5321h6f7f691_0    bioconda
boost-cpp                 1.82.0               h8013b2b_2    conda-forge
brotli                    1.0.9                h166bdaf_9    conda-forge
brotli-bin                1.0.9                h166bdaf_9    conda-forge
brotli-python             1.0.9            py39h5a03fae_9    conda-forge
bx-python                 0.10.0           py39h31164c1_0    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
c-compiler                1.6.0                hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cd-hit                    4.8.1                h43eeafb_9    bioconda
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39he91dace_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
cmake                     3.26.4               hcfe8598_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0            py39h7633fee_0    conda-forge
curl                      8.1.2                h409715c_0    conda-forge
cxx-compiler              1.6.0                h00ab1b0_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dbus                      1.13.18              hb2f20db_0
diamond                   2.1.8                h43eeafb_0    bioconda
eigen                     3.3.9                h4bd325d_1    conda-forge
entrez-direct             16.2                 he881be0_1    bioconda
expat                     2.5.0                hcb278e6_1    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonttools                 4.42.1           py39hd1e30aa_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gcc                       12.3.0               h8d2909c_1    conda-forge
gcc_impl_linux-64         12.3.0               he2b93b0_0    conda-forge
gcc_linux-64              12.3.0               h76fc315_1    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gffutils                  0.12               pyh7cba7a3_0    bioconda
ggcaller                  1.3.4                    pypi_0    pypi
glib                      2.76.4               hfc55251_0    conda-forge
glib-tools                2.76.4               hfc55251_0    conda-forge
gst-plugins-base          1.14.1               h6a678d5_1
gstreamer                 1.14.1               h5eee18b_1
gxx                       12.3.0               h8d2909c_1    conda-forge
gxx_impl_linux-64         12.3.0               he2b93b0_0    conda-forge
gxx_linux-64              12.3.0               h8a814eb_1    conda-forge
hmmer                     3.3.2                hdbdd923_4    bioconda
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-resources       6.0.1              pyhd8ed1ab_0    conda-forge
importlib_resources       6.0.1              pyhd8ed1ab_0    conda-forge
intbitset                 2.4.1            py39hb9d737c_3    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_16    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py39h7633fee_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0            16_linux64_mkl    conda-forge
libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
libbrotlidec              1.0.9                h166bdaf_9    conda-forge
libbrotlienc              1.0.9                h166bdaf_9    conda-forge
libcblas                  3.9.0            16_linux64_mkl    conda-forge
libclang                  14.0.6          default_h7634d5b_1    conda-forge
libclang13                14.0.6          default_h9986a30_1    conda-forge
libcups                   2.3.3                h36d4200_3    conda-forge
libcurl                   8.1.2                h409715c_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     12.3.0               h8bca6fd_0    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libglib                   2.76.4               hebfc3b9_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libhwloc                  2.9.2           default_h554bfaf_1009    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
liblapack                 3.9.0            16_linux64_mkl    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     12.15                hdbd6064_1
libprotobuf               3.19.6               h3eb15da_0    conda-forge
libsanitizer              12.3.0               h0f45ef3_0    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-devel_linux-64  12.3.0               h8bca6fd_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtiff                   4.3.0                h0fcbabc_4    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.44.2               hd590300_1    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxkbcommon              1.5.0                h5d7e998_3    conda-forge
libxml2                   2.11.5               h232c23b_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               16.0.6               h4dfa4b3_0    conda-forge
mafft                     7.520                h031d066_2    bioconda
make                      4.3                  hd18ef5c_1    conda-forge
matplotlib                3.7.2            py39hf3d152e_0    conda-forge
matplotlib-base           3.7.2            py39h0126182_0    conda-forge
mkl                       2022.2.1         h84fe81f_16997    conda-forge
mkl-devel                 2022.2.1         ha770c72_16998    conda-forge
mkl-include               2022.2.1         h84fe81f_16997    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql                     5.7.20            hf484d3e_1001    conda-forge
ncbi-vdb                  3.0.0           pl5321h87f3376_0    bioconda
ncurses                   6.4                  hcb278e6_0    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
ninja                     1.11.1               h924138e_0    conda-forge
numpy                     1.25.2           py39h6183b62_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openblas                  0.3.23          pthreads_h855a84d_0    conda-forge
openjpeg                  2.5.0                h7d73246_0    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.1.0            py39hddac248_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
perl                      5.32.1          4_hd590300_perl5    conda-forge
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h166bdaf_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h166bdaf_0    conda-forge
perl-encode               3.19            pl5321h166bdaf_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-io-compress          2.201           pl5321hdbdd923_2    bioconda
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321h4ac6f70_6    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321h031d066_2    bioconda
perl-parent               0.241           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321h166bdaf_0    conda-forge
perl-scalar-list-utils    1.63            pl5321h166bdaf_0    conda-forge
perl-storable             3.15            pl5321h166bdaf_0    conda-forge
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
pillow                    8.4.0            py39ha612740_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
protobuf                  3.19.6           py39h227be39_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pybind11                  2.11.1           py39h7633fee_0    conda-forge
pybind11-global           2.11.1           py39h7633fee_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyfaidx                   0.7.2.1            pyh7cba7a3_1    bioconda
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.4           py39h5a03fae_0    conda-forge
pyqt5-sip                 12.9.0           py39h5a03fae_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.18          h0755675_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-edlib              1.3.9            py39h1f90b4d_4    bioconda
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python-wget               3.2                        py_0    conda-forge
python_abi                3.9                      3_cp39    conda-forge
pytorch                   1.10.2          cpu_py39h5e9ed0b_1    conda-forge
pytorch-cpu               1.10.2          cpu_py39h718b53a_1    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyvcf3                    1.0.3              pyhdfd78af_0    bioconda
qt-main                   5.15.2              h53bd1ea_10
rapidnj                   2.3.2                h4ac6f70_4    bioconda
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rhash                     1.4.3                hd590300_2    conda-forge
scipy                     1.11.2           py39h6183b62_0    conda-forge
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
setuptools                59.5.0           py39hf3d152e_0    conda-forge
simplejson                3.19.1           py39h72bdee0_0    conda-forge
sip                       6.5.1            py39he80948d_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
snp-sites                 2.5.1                he4a0461_4    bioconda
sqlite                    3.43.0               h2c6b66d_0    conda-forge
statsmodels               0.14.0           py39h0f8d45d_1    conda-forge
sysroot_linux-64          2.12                he073ed8_16    conda-forge
tbb                       2021.10.0            h00ab1b0_0    conda-forge
tbb-devel                 2021.10.0            h00ab1b0_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.3.3            py39hd1e30aa_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
uncertainties             3.1.7              pyhd8ed1ab_0    conda-forge
unicodedata2              15.0.0           py39hb9d737c_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xkeyboard-config          2.39                 hd590300_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```
Biopython version is certainly different (1.78 vs 1.80). Not sure if that was the only cause of the previous issues, python is also different (3.10 vs 3.9).

I'll try to do a test run with the dataset from the tutorial and let you know if I run into further issues. Thank you!

**Comment by samhorsfield96** [comment]
Hi, the conda installation doesn't work currently due to dependency issues with mkl and pytorch. The best way to install is from source or using docker (see https://ggcaller.readthedocs.io/en/latest/installation.html). The depreciation warnings should be fine, please let me know if you run into any issues!
