### ISSUE TITLE
ImportError: cannot import name 'UnknownSeq' from 'Bio.Seq'

### ISSUE THREAD

**Issue by Czirion** [samhorsfield96/ggCaller#6]
Hi,

I tried the installation through conda and from source in 3 different computers and get very similar error messages when I test with "ggcaller --help".

This is the error with the installation from source:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/ggc_env/bin/ggcaller", line 33, in <module>
    sys.exit(load_entry_point('ggCaller==1.3.3', 'console_scripts', 'ggcaller')())
  File "/home/user/anaconda3/envs/ggc_env/bin/ggcaller", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/user/anaconda3/envs/ggc_env/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/user/anaconda3/envs/ggc_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/user/anaconda3/envs/ggc_env/lib/python3.9/site-packages/ggCaller-1.3.3-py3.9-linux-x86_64.egg/ggCaller/__main__.py", line 12, in <module>
    from panaroo_runner.__main__ import run_panaroo
  File "/home/user/anaconda3/envs/ggc_env/lib/python3.9/site-packages/ggCaller-1.3.3-py3.9-linux-x86_64.egg/panaroo_runner/__main__.py", line 12, in <module>
    from .generate_output import *
  File "/home/user/anaconda3/envs/ggc_env/lib/python3.9/site-packages/ggCaller-1.3.3-py3.9-linux-x86_64.egg/panaroo_runner/generate_output.py", line 14, in <module>
    from BCBio import GFF
  File "/home/user/anaconda3/envs/ggc_env/lib/python3.9/site-packages/BCBio/GFF/__init__.py", line 3, in <module>
    from BCBio.GFF.GFFParser import GFFParser, DiscoGFFParser, GFFExaminer, parse, parse_simple
  File "/home/user/anaconda3/envs/ggc_env/lib/python3.9/site-packages/BCBio/GFF/GFFParser.py", line 34, in <module>
    from Bio.Seq import UnknownSeq
ImportError: cannot import name 'UnknownSeq' from 'Bio.Seq' (/home/user/anaconda3/envs/ggc_env/lib/python3.9/site-packages/Bio/Seq.py)

Thanks!

**Comment by samhorsfield96** [comment]
Hi, could you run `conda list` in the ggCaller environment and paste the output here, please? There may be an issue with some of the dependency versions.

**Comment by benrhodes26** [comment]
I had this [issue](https://github.com/samhorsfield96/ggCaller/issues/7). I think you need the version of biopython needs pinning to 1.7.9 in the environment.yml file.

**Comment by samhorsfield96** [comment]
The latest version of biopython (v1.81) has removed the UnknownSeq object. @benrhodes26 has kindly looked into this - in the ggcaller environment run `conda install biopython=1.80` (UnknownSeq is also still available in this version) and retry running ggCaller as before.

**Comment by Czirion** [comment]
Hi, 

Thank you very much @samhorsfield96  and @benrhodes26!

Installing the biopython version 1.80 worked!
